apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app.kubernetes.io/component: orchestrator
    app.kubernetes.io/instance: local-sense-orchestrator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: local-sense-orchestrator-sense
    helm.sh/chart: sense-orchestrator-1.12.0
  name: local-sense-orchestrator-sense-orch
  namespace: iri
  resourceVersion: "10846219995"
  uid: b40971bc-2f97-41bd-ae34-ccdc3f0753aa
spec:
  minReadySeconds: 10
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/component: orchestrator
      app.kubernetes.io/instance: local-sense-orchestrator
      app.kubernetes.io/name: local-sense-orchestrator-sense
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        link.argocd.argoproj.io/external-link: https://sense-o-iri.nrp-nautilus.io/StackV-web/portal/
        stackv/tag: dev-polling-test
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: orchestrator
        app.kubernetes.io/instance: local-sense-orchestrator
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: local-sense-orchestrator-sense
        helm.sh/chart: sense-orchestrator-1.12.0
      name: local-sense-orchestrator-sense-orch
    spec:
      tolerations:
        - effect: NoSchedule
          key: nautilus.io/system
          operator: Exists
        - effect: NoSchedule
          key: nautilus.io/reservation
          operator: Exists
        - effect: PreferNoSchedule
          key: nvidia.com/gpu
          operator: Exists
      containers:
      - command:
        - sh
        - -c
        - |
          /bin/wait-for-it.sh local-sense-orchestrator-sense-mysql:3306 -t 600 -s -- /bin/startup.sh
        env:
        - name: KC_DOMAIN
          valueFrom:
            secretKeyRef:
              key: host
              name: sense-auth-cred
        - name: KC_CLIENT
          valueFrom:
            secretKeyRef:
              key: client
              name: sense-auth-cred
        - name: KC_SECRET
          valueFrom:
            secretKeyRef:
              key: client-secret
              name: sense-auth-cred
        - name: NO_SERVER_KEYSTORE
          value: "true"
        - name: DB_HOST
          value: local-sense-orchestrator-sense-mysql:3306
        - name: JAVA_MEMORY
          value: 4G
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              key: mysql-password
              name: sense-cred
        - name: TLS_PASS
          valueFrom:
            secretKeyRef:
              key: tls-password
              name: sense-cred
        - name: MAIL_PORT
          value: "587"
        - name: MAIL_HOST
          value: smtp.office365.com
        - name: MAIL_USER
          value: example@outlook.com
        - name: MAIL_PASS
          valueFrom:
            secretKeyRef:
              key: mail-password
              name: sense-cred
        image: virnao/sense-orchestrator:dev-dualstack
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 5
        name: local-sense-orchestrator-sense-orch
        ports:
        - containerPort: 8443
          name: app-https
          protocol: TCP
        - containerPort: 8080
          name: app-http
          protocol: TCP
        - containerPort: 9990
          name: console-http
          protocol: TCP
        - containerPort: 9993
          name: console-https
          protocol: TCP
        - containerPort: 8787
          name: app-debug
          protocol: TCP
        readinessProbe:
          failureThreshold: 9
          httpGet:
            path: /StackV-web/portal/
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 60
        resources:
          limits:
            cpu: "32"
            memory: 64Gi
          requests:
            cpu: "16"
            memory: 32Gi
        startupProbe:
          failureThreshold: 24
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 5
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/jboss/wildfly/standalone/configuration/tls
          name: client-keystore
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - deploy
        - -t
        - db:mysql://$(SQITCH_USER):$(SQITCH_PASSWORD)@$(SQITCH_DB_HOST)/frontend
        env:
        - name: SQITCH_USER
          value: root
        - name: SQITCH_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mysql-password
              name: sense-cred
        - name: SQITCH_DB_HOST
          value: local-sense-orchestrator-sense-mysql:3306
        image: virnao/sense-db-migration:dev-polling-test-frontend
        imagePullPolicy: Always
        name: local-sense-orchestrator-sense-orch-db-init-frontend
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - args:
        - deploy
        - -t
        - db:mysql://$(SQITCH_USER):$(SQITCH_PASSWORD)@$(SQITCH_DB_HOST)/rainsdb
        env:
        - name: SQITCH_USER
          value: root
        - name: SQITCH_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mysql-password
              name: sense-cred
        - name: SQITCH_DB_HOST
          value: local-sense-orchestrator-sense-mysql:3306
        image: virnao/sense-db-migration:dev-polling-test
        imagePullPolicy: Always
        name: local-sense-orchestrator-sense-orch-db-init
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      nodeSelector:
        # nautilus.io/ipv6: "true"
        kubernetes.io/hostname: k8s-gen5-02.sdsc.optiputer.net
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: client-keystore
        secret:
          defaultMode: 420
          secretName: sense-keystores
status:
  conditions:
  - lastTransitionTime: "2025-07-17T19:04:37Z"
    lastUpdateTime: "2025-07-22T21:23:18Z"
    message: ReplicaSet "local-sense-orchestrator-sense-orch-77b8bcc478" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-07-22T21:35:38Z"
    lastUpdateTime: "2025-07-22T21:35:38Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 33
