{{- include "sitermagent.validateDeploymentType" . }}
{{- if (include "sitermagent.logstorageEnabled" . | trim | eq "true") }}
{{- $logstorage := get .Values "logstorage" | default dict }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ get $logstorage "volname" | default (printf "pvclog-%s" (include "sitermagent.truncname" .)) }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ get $logstorage "capacity" | default "5Gi" }}
  storageClassName: {{ get $logstorage "storageClassName" | default "standard" }}
{{- end }}
