---
kind: ConfigMap
apiVersion: v1
metadata:
  name: conf-{{ template "sitefe.truncname" . }}
  namespace: {{ .Values.namespace }}
data:
  sense-siterm-fe: |
    ---
{{- if .Values.gitrepo }}
    GIT_REPO: {{ .Values.gitrepo }}
{{- end }}
{{- if .Values.gitbranch }}
    GIT_BRANCH: {{ .Values.gitbranch }}
{{- end }}
{{- if .Values.giturl }}
    GIT_URL: {{ .Values.giturl }}
{{- end }}
    SITENAME: {{ .Values.sitename }}
{{- if .Values.md5 }}
    MD5: {{ .Values.md5 }}
{{- end }}
{{- if .Values.manualConfig.enabled }}
    MAPPING_TYPE: FE
    MAIN_CONFIG_FILE: /etc/siterm-config/main.yaml
    AUTH_CONFIG_FILE: /etc/siterm-config/auth.yaml
{{- if .Values.manualConfig.auth_re }}
    AUTH_RE_CONFIG_FILE: /etc/siterm-config/auth-re.yaml
{{- end }}
  manual-main: |
{{ .Values.manualConfig.main | indent 4 }}
  manual-auth: |
{{ .Values.manualConfig.auth | indent 4 }}
{{- if .Values.manualConfig.auth_re }}
  manual-auth-re: |
{{ .Values.manualConfig.auth_re | indent 4 }}
{{- end }}
{{- end }}
