---
kind: ConfigMap
apiVersion: v1
metadata:
  name: conf-{{ template "sitefe.truncname" . }}
  namespace: {{ .Values.namespace }}
data:
  sense-siterm-fe: |
    ---
{{- if .Values.gitrepo }}
    GIT_REPO: {{ .Values.gitrepo }}
{{- end }}
{{- if .Values.gitbranch }}
    GIT_BRANCH: {{ .Values.gitbranch }}
{{- end }}
{{- if .Values.giturl }}
    GIT_URL: {{ .Values.giturl }}
{{- end }}
    SITENAME: {{ .Values.sitename }}
{{- if .Values.md5 }}
    MD5: {{ .Values.md5 }}
{{- end }}
