{{- if (include "sitefe.storageEnabled" . | trim | eq "true") }}
{{- $storage := get .Values "storage" | default dict }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ get $storage "volname" | default (printf "pvc-%s" (include "sitefe.truncname" .)) }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ get $storage "capacity" | default "5Gi" }}
  storageClassName: {{ get $storage "storageClassName" | default "standard" }}
{{- end }}
